In [1]:
import pandas as pd
import os

In [2]:
df = pd.read_csv("df_main.csv")
df

,Unnamed: 0,category,beverage,food,rating,recipeName,nutrition,ingred,ingr_count
0,0,White Wine,Sancerre,Chevre Cheese,5.0,chevre cheese stuffed mushrooms,"[260.2, 32.0, 10.0, 17.0, 20.0, 68.0, 2.0]","['mushrooms', 'butter', 'chevre cheese', 'seas...",5.0
1,1,White Wine,Sancerre,Goat Cheese,5.0,chive goat cheese mashed potatoes,"[269.3, 25.0, 7.0, 15.0, 14.0, 52.0, 8.0]","['baking potatoes', 'garlic cloves', 'sour cre...",8.0
2,2,White Wine,"Gewürztraminer, Alsace",Muenster Cheese,5.0,chicken with muenster cheese,"[414.4, 36.0, 6.0, 26.0, 63.0, 55.0, 4.0]","['chicken breasts', 'eggs', 'seasoned bread cr...",6.0
3,3,Dessert Wine,Sauternes,Roquefort Cheese,5.0,honeydew melon with roquefort cheese,"[226.2, 8.0, 162.0, 13.0, 9.0, 16.0, 14.0]","['water', 'honey', 'orange zest', 'lemon zest'...",7.0
4,4,Dessert Wine,Banyuls,Dark Chocolate,5.0,death by chocolate copycat dark chocolate sauce,"[80.9, 1.0, 67.0, 0.0, 2.0, 2.0, 6.0]","['cocoa', 'sugar', 'water']",3.0
...,...,...,...,...,...,...,...,...,...
7780,7780,White Wine,Grenache Blanc,Roasted Peppers,3.0,farfalle with goat cheese and roasted peppers,"[769.6, 49.0, 17.0, 56.0, 56.0, 69.0, 30.0]","['farfalle pasta', 'goat cheese', 'roasted red...",8.0
7781,7781,White Wine,Grenache Blanc,Marjoram,3.0,steamed broccoli and corn with marjoram,"[64.1, 0.0, 3.0, 0.0, 5.0, 0.0, 4.0]","['frozen corn', 'broccoli', 'water', 'marjoram']",4.0
7782,7782,Red Wine,Beaujolais,Seafood Macaroni and Cheese,2.5,NaN,NaN,NaN,NaN
7783,7783,Red Wine,Cabernet Sauvignon,Dark Chocolate,2.0,death by chocolate copycat dark chocolate sauce,"[80.9, 1.0, 67.0, 0.0, 2.0, 2.0, 6.0]","['cocoa', 'sugar', 'water']",3.0
7784,7784,Red Wine,Pinot Noir,Seafood Macaroni and Cheese,2.0,NaN,NaN,NaN,NaN

In [7]:
red_df = df[df["category"] == "Red Wine"]
cab_df = red_df[red_df["beverage"]=="Cabernet Sauvignon"]
cab_df

,Unnamed: 0,category,beverage,food,rating,recipeName,nutrition,ingred,ingr_count
26,26,Red Wine,Cabernet Sauvignon,Steak,5.0,alouette crumbled goat cheese ny grilled strip...,"[669.6, 73.0, 5.0, 10.0, 104.0, 95.0, 1.0]","['strip steaks', 'shallot', 'fresh lemon juice...",9.0
39,39,Red Wine,Cabernet Sauvignon,Ribeye Steak,5.0,NaN,NaN,NaN,NaN
112,112,Red Wine,Cabernet Sauvignon,Cheddar Cheese,4.5,cheddar cheese corn fritters,"[82.6, 5.0, 7.0, 6.0, 5.0, 10.0, 3.0]","['all-purpose flour', 'baking powder', 'salt',...",12.0
284,284,Red Wine,Cabernet Sauvignon,Hamburgers,4.5,a 1 hamburgers,"[243.8, 26.0, 0.0, 27.0, 42.0, 33.0, 0.0]","['ground beef', 'salt', 'a.1. original sauce']",3.0
307,307,Red Wine,Cabernet Sauvignon,Lamb Chops,4.5,seared lamb chops with a goat cheese white win...,"[74.0, 6.0, 3.0, 16.0, 6.0, 14.0, 0.0]","['sea salt', 'fresh ground pepper', 'lamb chop...",8.0
...,...,...,...,...,...,...,...,...,...
7694,7694,Red Wine,Cabernet Sauvignon,Lamb Kebabs,3.5,apricot lamb kebabs,"[562.1, 49.0, 106.0, 4.0, 73.0, 54.0, 11.0]","['lamb', 'apricot nectar', 'dried apricots', '...",11.0
7731,7731,Red Wine,Cabernet Sauvignon,Kidneys,3.5,kidneys in italian sauce,"[277.1, 24.0, 8.0, 22.0, 45.0, 36.0, 3.0]","['beef kidney', 'plain flour', 'salt and peppe...",10.0
7767,7767,Red Wine,Cabernet Sauvignon,Blue Cheese,1.5,blue cheese corn bread,"[346.6, 21.0, 50.0, 31.0, 20.0, 29.0, 14.0]","['jiffy corn muffin mix', 'egg', 'milk', 'blue...",6.0
7768,7768,Red Wine,Cabernet Sauvignon,Danish Blue Cheese,1.5,danish blue cheese and port spread,"[1388.2, 196.0, 21.0, 88.0, 83.0, 305.0, 5.0]","['danish blue cheese', 'unsalted butter', 'por...",6.0
7783,7783,Red Wine,Cabernet Sauvignon,Dark Chocolate,2.0,death by chocolate copycat dark chocolate sauce,"[80.9, 1.0, 67.0, 0.0, 2.0, 2.0, 6.0]","['cocoa', 'sugar', 'water']",3.0

In [40]:
for e in df

Ratatouille            1
Blue Cheese            1
Grilled Eggplant       1
Steak and Mushrooms    1
Veal Chops             1
                      ..
Turkey Roasted         1
Shark                  1
Danish Blue Cheese     1
Lamb Kebabs            2
Kidneys                2
Name: Food, Length: 139, dtype: int64

In [38]:
pair_df["Food"].unique()

array(['Steak', 'Ribeye Steak ', 'Cheddar Cheese', 'Hamburgers',
       'Lamb Chops', 'Roasted Lamb', 'Lamb Shanks', 'Meatloaf', 'Mint',
       'Black Pepper', 'Squab', 'Squab Roasted',
       'Steak with Black Pepper', 'Steak Filet Mignon', 'Grilled Steak',
       'Steak Rib Eye', 'NY Strip Steak', 'BBQ Ribs', 'Roast Beef',
       'Beef Stew', 'Brie Cheese', 'Camembert Cheese', 'Gouda Cheese',
       'Monterey Jack Cheese', 'Chicken', 'Chicken with Paprika',
       'Chicken Tikka Masala', 'Duck', 'Duck Confit', 'Grilled Dishes',
       'Grilled Hamburgers', 'Herbed Dishes', 'Lamb', 'Lamb Burgers',
       'Grilled Lamb', 'Roasted Leg of Lamb', 'Lamb Stew', 'Oregano',
       'Quail', 'Rosemary', 'Tête de Veau', 'Southwestern Cuisine',
       'Steak and Mushrooms', 'Steak Porterhouse', 'Steak Rare',
       'Steak Medium Rare', 'Steak Sirloin', 'Thyme', 'Grilled Tuna',
       'Turkey', 'Turkey Roasted', 'Veal', 'Veal Chops', 'Veal Roasted',
       'Venison', 'Farsumagru', 'Ostrich Burgers', 'Ostrich',
       'Shimofuri Teppan (wagyu steak)', 'Beef Teriyaki', 'Basil',
       'Bay Leaf', 'Beef', 'Beef Casserole', 'Cold Beef',
       'Beef Pot Roast', 'Beef Prime Rib', 'Beef Rib Roast',
       'Beef Short Ribs', 'Beef Stir Fried', 'Beef Strognaoff',
       'Beef Tacos', 'Beets', 'Berries', 'Bitter Food', 'Wild Boar',
       'Braised Dishes', 'Caribbean Cusine', 'Cauliflower',
       'Havarti Cheese', 'Parmesan Cheese', "Pont-L'eveque Cheese",
       'Port Salut Cheese', 'Provolone Cheese', 'Roquefort Cheese',
       'Teleme Cheese', 'Cherry', 'Chiles', 'Pasilla Chilie', 'Chili',
       'Duck with Fruit Sauce', 'Grilled Duck', 'Roasted Duck',
       'Grilled Eggplant', 'Ethiopian Cuisine', 'Fajitas with Steak',
       'Meat Fondue', 'Game', 'Game Birds', 'Garlic Roasted',
       'Goat Barbecued', 'Indian Cuisine', 'Kidneys', 'Lamb Kebabs',
       'Snickers Chocolate Bar', 'Arugula', 'Impossible Burger',
       'Beef Wellington', 'Cajun Jambalaya - Beef/Sausage',
       'Chili Con Carne', "Appleby's Cheese", 'Wild Boar Barbecued',
       'Walnuts', 'Tuna', 'Swordfish with Peppercorn Crust',
       'Swordfish with Black Pepper', 'Swordfish', 'Steak Tartare',
       'Steak Frites', 'Steak Chicken Fried', "Shepherd's Pie", 'Shark',
       'Ratatouille', 'Pizza', 'Pheasant', 'Green Bell Pepper',
       'Red Bell Pepper', 'Pasta Bolognese', 'Osso Buco', 'Nutmeg',
       'Portobello Mushrooms', 'Grilled Portobello Mushrooms',
       'Shitake Mushrooms', 'Morel Mushrooms', 'Moroccan Cuisine',
       'Mexican Cuisine (beef based)', 'Blue Cheese',
       'Danish Blue Cheese', 'Dark Chocolate'], dtype=object)