In [40]:
import pandas as pd
import pickle as pkl
import os
import numpy as np
from ast import literal_eval

In [10]:
with open('ingr_map.pkl', 'rb') as f:
    data = pkl.load(f)
data

,raw_ingr,raw_words,processed,len_proc,replaced,count,id
0,"medium heads bibb or red leaf lettuce, washed,...",13,"medium heads bibb or red leaf lettuce, washed,...",73,lettuce,4507,4308
1,mixed baby lettuces and spring greens,6,mixed baby lettuces and spring green,36,lettuce,4507,4308
2,romaine lettuce leaf,3,romaine lettuce leaf,20,lettuce,4507,4308
3,iceberg lettuce leaf,3,iceberg lettuce leaf,20,lettuce,4507,4308
4,red romaine lettuce,3,red romaine lettuce,19,lettuce,4507,4308
...,...,...,...,...,...,...,...
11654,soybeans,1,soybean,7,soybean,31,6702
11655,goose,1,goose,5,goose,8,3318
11656,ajwain,1,ajwain,6,ajwain,13,47
11657,brinjals,1,brinjal,7,brinjal,2,750
11658,khoya,1,khoya,5,khoya,6,4061

In [11]:
data = pd.DataFrame(data)
data = data.drop(columns = ['raw_ingr','raw_words','processed','len_proc','count'])

In [12]:
data = data.drop_duplicates()
data = dict(zip(data['id'], data['replaced']))

In [13]:
recipe_df = pd.read_csv('PocketSom/RAW_recipes.csv')
recipe_df = recipe_df.set_index('id').sort_index()
recipe_df

,name,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients
id,,,,,,,,,,,
38,low fat berry blue frozen dessert,1485,1533,1999-08-09,"['weeknight', 'time-to-make', 'course', 'prepa...","[170.9, 3.0, 120.0, 1.0, 6.0, 6.0, 12.0]",13,"['toss 2 cups berries with sugar', 'let stand ...","this is yummy and low-fat, it always turns out...","['blueberries', 'granulated sugar', 'vanilla y...",4
39,biryani,265,1567,1999-08-29,"['weeknight', 'time-to-make', 'course', 'main-...","[1110.7, 90.0, 81.0, 15.0, 126.0, 82.0, 28.0]",17,['soak saffron in warm milk for 5 minutes and ...,"delhi, india","['saffron', 'milk', 'hot green chili peppers',...",26
40,best lemonade,35,1566,1999-09-05,"['60-minutes-or-less', 'time-to-make', 'course...","[311.1, 0.0, 308.0, 0.0, 0.0, 0.0, 27.0]",8,"['into a 1 quart jar with tight fitting lid , ...",this is from one of my first good house keepi...,"['sugar', 'lemons, rind of', 'fresh water', 'f...",6
41,carina s tofu vegetable kebabs,1460,1586,1999-09-03,"['weeknight', 'time-to-make', 'course', 'main-...","[536.1, 36.0, 128.0, 64.0, 58.0, 19.0, 21.0]",18,"['drain the tofu , carefully squeezing out exc...",this dish is best prepared a day in advance to...,"['extra firm tofu', 'eggplant', 'zucchini', 'r...",15
43,best blackbottom pie,140,34879,1999-08-21,"['weeknight', 'time-to-make', 'course', 'cuisi...","[437.9, 29.0, 170.0, 11.0, 13.0, 54.0, 19.0]",35,"['graham cracker crust: in small bowl , combin...","sweet, chocolatey, yummy","['graham cracker crumbs', 'sugar', 'butter', '...",15
...,...,...,...,...,...,...,...,...,...,...,...
537459,bailey s chocotini,10,400708,2018-11-10,"['15-minutes-or-less', 'time-to-make', 'course...","[220.7, 15.0, 49.0, 2.0, 3.0, 30.0, 4.0]",5,"['to layer: add chocolate liqueur to glass', '...",a recipe that recipe complements the cocoa in ...,"['baileys irish cream', 'chocolate liqueur', '...",3
537485,5 ingredient salted caramel crumble bars,45,2000378667,2018-11-12,"['60-minutes-or-less', 'time-to-make', 'course...","[52.8, 3.0, 0.0, 4.0, 1.0, 1.0, 2.0]",21,"['1', 'heat oven to 350f spray 8-inch square p...",delicious,"['pillsbury sugar cookie dough', 'caramel topp...",5
537543,moist gingerbread cake,55,2001201872,2018-11-16,"['60-minutes-or-less', 'time-to-make', 'course...","[1617.0, 104.0, 213.0, 8.0, 40.0, 203.0, 80.0]",8,"['preheat the oven to 350&deg', 'f grease a lo...",a slightly sticky loaf cake flavoured with gin...,"['unsalted butter', 'applesauce', 'egg', 'unsu...",10
537671,nutcracker peppermint red velvet cake pops,135,2002198506,2018-11-28,"['time-to-make', 'course', 'preparation', 'occ...","[207.9, 12.0, 93.0, 10.0, 6.0, 8.0, 10.0]",54,"['before you begin , you will need to gather t...",rich red velvet cake combines with cool pepper...,"[""devil's food cake mix"", 'eggs', 'buttermilk'...",12
537716,mini buffalo chicken cheesesteaks,40,2001975627,2018-12-04,"['60-minutes-or-less', 'time-to-make', 'course...","[407.9, 34.0, 21.0, 49.0, 28.0, 64.0, 12.0]",12,['heat 1 tablespoon of olive oil in a skillet ...,these party-style chicken cheesesteaks are fla...,"['olive oil', 'green bell pepper', 'yellow oni...",13

In [14]:
pp_recipe_df = pd.read_csv('PP_recipes.csv')
pp_recipe_df = pp_recipe_df.set_index(['id']).sort_index()
pp_recipe_df

,i,name_tokens,ingredient_tokens,steps_tokens,techniques,calorie_level,ingredient_ids
id,,,,,,,
38,16791,"[40480, 954, 4739, 6449, 1674, 4787, 10601, 40...","[[12698, 11125], [4465, 29487, 6444], [15000, ...","[40480, 40482, 8263, 280, 7420, 11125, 556, 64...","[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,"[648, 3355, 7501, 4253]"
40,99809,"[40480, 1432, 17746, 40481]","[[6444], [30295, 240, 17, 686, 498], [3137, 13...","[40480, 40482, 666, 246, 277, 660, 2212, 7932,...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,"[6906, 4303, 2919, 2832, 3829, 1567]"
45,84204,"[40480, 6796, 5940, 7056, 556, 32669, 5776, 32...","[[6444], [7424, 745], [8441], [8441, 15953], [...","[40480, 40482, 729, 2525, 10906, 485, 43, 2885...","[1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,"[6906, 4574, 2499, 2509, 2683, 6270, 869, 3324..."
46,172842,"[40480, 246, 31704, 30710, 25199, 40481]","[[6878, 26285], [477, 869, 27, 14861], [548, 2...","[40480, 40482, 8654, 481, 30710, 500, 1667, 29...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,[6082]
49,61982,"[40480, 5867, 6285, 518, 892, 489, 5385, 40481]","[[3137, 19104], [8780], [31801, 918, 15509, 58...","[40480, 40482, 5539, 19104, 500, 280, 3, 21, 3...","[1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, ...",2,"[2847, 840, 1254, 2683, 4593, 1257, 6270, 4836..."
...,...,...,...,...,...,...,...
537175,78714,"[40480, 9194, 3779, 28058, 1431, 523, 5825, 40...","[[2832, 1431, 523], [2107, 1353], [4017], [313...","[40480, 40482, 729, 2525, 481, 10906, 485, 266...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, ...",0,"[7956, 7650, 3723, 6283, 6270, 2499, 63]"
537319,115103,"[40480, 18376, 16361, 30084, 40481]","[[4017], [2507, 6444], [15000, 18347], [18376,...","[40480, 40482, 729, 2525, 704, 10906, 485, 43,...","[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",2,"[3723, 800, 7470, 5764, 7557, 4998, 5298, 3311]"
537458,18718,"[40480, 15022, 488, 16084, 17921, 10837, 40481]","[[8450, 25489, 2883, 10837], [4914, 6821], [87...","[40480, 40482, 1082, 10837, 488, 1353, 485, 24...","[0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,"[8012, 1910, 840, 6654, 3670, 2776, 2856, 3203..."
537485,163262,"[40480, 284, 33571, 31331, 19411, 18777, 5639,...","[[2715, 26, 26256, 6444, 11274, 17532], [19411...","[40480, 40482, 277, 40478, 40482, 2525, 10906,...","[1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",0,"[6909, 1076, 63, 1574, 5298]"
537716,72400,"[40480, 10025, 17476, 5867, 18359, 21170, 40481]","[[10444, 6020], [2056, 4178, 11332], [3484, 21...","[40480, 40482, 2525, 277, 13020, 9082, 498, 10...","[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...",1,"[5006, 3399, 7979, 6270, 5319, 1240, 3668, 822..."

In [15]:

recipe_df['ingredient_ids'] = pp_recipe_df['ingredient_ids']
recipe_df = recipe_df[recipe_df['ingredient_ids'].notna()]
recipe_df

,name,minutes,contributor_id,submitted,tags,nutrition,n_steps,steps,description,ingredients,n_ingredients,ingredient_ids
id,,,,,,,,,,,,
38,low fat berry blue frozen dessert,1485,1533,1999-08-09,"['weeknight', 'time-to-make', 'course', 'prepa...","[170.9, 3.0, 120.0, 1.0, 6.0, 6.0, 12.0]",13,"['toss 2 cups berries with sugar', 'let stand ...","this is yummy and low-fat, it always turns out...","['blueberries', 'granulated sugar', 'vanilla y...",4,"[648, 3355, 7501, 4253]"
40,best lemonade,35,1566,1999-09-05,"['60-minutes-or-less', 'time-to-make', 'course...","[311.1, 0.0, 308.0, 0.0, 0.0, 0.0, 27.0]",8,"['into a 1 quart jar with tight fitting lid , ...",this is from one of my first good house keepi...,"['sugar', 'lemons, rind of', 'fresh water', 'f...",6,"[6906, 4303, 2919, 2832, 3829, 1567]"
45,buttermilk pie with gingersnap crumb crust,80,1580,1999-08-06,"['weeknight', 'time-to-make', 'course', 'main-...","[228.0, 10.0, 98.0, 11.0, 8.0, 8.0, 12.0]",10,"['preheat oven to 350f', 'make pie crust , usi...",yum,"['sugar', 'margarine', 'egg', 'egg whites', 'f...",9,"[6906, 4574, 2499, 2509, 2683, 6270, 869, 3324..."
46,a jad cucumber pickle,25,1533,1999-08-11,"['30-minutes-or-less', 'time-to-make', 'course...","[4.3, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]",5,"['slice the cucumber in four lengthwise , then...",it is a traditional accompaniment to snacks su...,"['rice vinegar', 'thangkwa', 'hom daeng', 'nam...",6,[6082]
49,chicken breasts lombardi,75,174711,1999-08-14,"['weeknight', 'time-to-make', 'course', 'main-...","[627.7, 38.0, 8.0, 35.0, 115.0, 64.0, 4.0]",22,['cook mushrooms in 2 tbsp butter in a large s...,"cheese, chicken, and mushrooms with marsala.","['fresh mushrooms', 'butter', 'boneless skinle...",10,"[2847, 840, 1254, 2683, 4593, 1257, 6270, 4836..."
...,...,...,...,...,...,...,...,...,...,...,...,...
537175,rapid rise skillet yeast rolls,55,400708,2018-10-13,"['60-minutes-or-less', 'time-to-make', 'course...","[159.4, 7.0, 23.0, 9.0, 7.0, 13.0, 8.0]",13,"['preheat the oven to 400 degrees f', 'in a la...",sometimes you need rolls fast. here's a perfec...,"['dry yeast', 'warm water', 'honey', 'salted b...",7,"[7956, 7650, 3723, 6283, 6270, 2499, 63]"
537319,pumpkin spice granola,50,400708,2018-10-25,"['60-minutes-or-less', 'time-to-make', 'course...","[614.0, 50.0, 155.0, 0.0, 18.0, 18.0, 26.0]",10,"['preheat your oven to 325 degrees', 'prepare ...",tastes just like pumpkin spice and is so addic...,"['honey', 'brown sugar', 'vanilla extract', 'p...",8,"[3723, 800, 7470, 5764, 7557, 4998, 5298, 3311]"
537458,garlic and herb mashed potatoes,42,400708,2018-11-10,"['60-minutes-or-less', 'time-to-make', 'course...","[390.8, 37.0, 12.0, 12.0, 11.0, 73.0, 12.0]",12,['place potatoes and water to cover in a 6-qt'...,cream cheese is the secret ingredient in these...,"['yukon gold potatoes', 'cream cheese', 'butte...",11,"[8012, 1910, 840, 6654, 3670, 2776, 2856, 3203..."
537485,5 ingredient salted caramel crumble bars,45,2000378667,2018-11-12,"['60-minutes-or-less', 'time-to-make', 'course...","[52.8, 3.0, 0.0, 4.0, 1.0, 1.0, 2.0]",21,"['1', 'heat oven to 350f spray 8-inch square p...",delicious,"['pillsbury sugar cookie dough', 'caramel topp...",5,"[6909, 1076, 63, 1574, 5298]"
537716,mini buffalo chicken cheesesteaks,40,2001975627,2018-12-04,"['60-minutes-or-less', 'time-to-make', 'course...","[407.9, 34.0, 21.0, 49.0, 28.0, 64.0, 12.0]",12,['heat 1 tablespoon of olive oil in a skillet ...,these party-style chicken cheesesteaks are fla...,"['olive oil', 'green bell pepper', 'yellow oni...",13,"[5006, 3399, 7979, 6270, 5319, 1240, 3668, 822..."

In [41]:
recipe_df['ingredient_ids'] = recipe_df['ingredient_ids'].apply(literal_eval)
recipe_df['ingredient_ids']

c:\users\samhr\.virtualenvs\pocket-somm-ivqvdwga\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

id
38                                  [648, 3355, 7501, 4253]
40                     [6906, 4303, 2919, 2832, 3829, 1567]
45        [6906, 4574, 2499, 2509, 2683, 6270, 869, 3324...
46                                                   [6082]
49        [2847, 840, 1254, 2683, 4593, 1257, 6270, 4836...
                                ...
537175             [7956, 7650, 3723, 6283, 6270, 2499, 63]
537319      [3723, 800, 7470, 5764, 7557, 4998, 5298, 3311]
537458    [8012, 1910, 840, 6654, 3670, 2776, 2856, 3203...
537485                         [6909, 1076, 63, 1574, 5298]
537716    [5006, 3399, 7979, 6270, 5319, 1240, 3668, 822...
Name: ingredient_ids, Length: 178265, dtype: object

In [43]:
recipe_df['clean_ingredients'] = recipe_df.ingredient_ids.apply(lambda x:list(filter(None,map(data.get,x))))

c:\users\samhr\.virtualenvs\pocket-somm-ivqvdwga\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

In [51]:
clean_df = recipe_df.drop(columns = ['minutes','contributor_id','submitted','n_steps','steps', 'description','ingredients','n_ingredients','ingredient_ids'])

#split and clean 'nutrition' column values, convert to float
clean_df[['calories (number)', 'total fat (PDV)', 'sugar (PDV)' , 'sodium (PDV)' , 'protein (PDV)' , 'saturated fat (PDV)', 'carbohydrates (PDV)']]=clean_df['nutrition'].str.split(', ', expand=True,n=6)
clean_df['calories (number)'] = clean_df['calories (number)'].str.lstrip('[')
clean_df['carbohydrates (PDV)'] = clean_df['carbohydrates (PDV)'].str.strip(']')
clean_df[['calories (number)', 'total fat (PDV)', 'sugar (PDV)' , 'sodium (PDV)' , 'protein (PDV)', 'saturated fat (PDV)', 'carbohydrates (PDV)']] = clean_df[['calories (number)', 'total fat (PDV)', 'sugar (PDV)' , 'sodium (PDV)' , 'protein (PDV)', 'saturated fat (PDV)', 'carbohydrates (PDV)']].astype(float)

#remove very high and very low calorie outliers
clean_df =clean_df[(clean_df["calories (number)"] <800) & (clean_df["calories (number)"] >175) & (clean_df['sugar (PDV)']<50)]
clean_df

,name,tags,nutrition,clean_ingredients,calories (number),total fat (PDV),sugar (PDV),sodium (PDV),protein (PDV),saturated fat (PDV),carbohydrates (PDV)
id,,,,,,,,,,,
49,chicken breasts lombardi,"['weeknight', 'time-to-make', 'course', 'main-...","[627.7, 38.0, 8.0, 35.0, 115.0, 64.0, 4.0]","[fresh mushroom, butter, chicken breast half, ...",627.7,38.0,8.0,35.0,115.0,64.0,4.0
58,low fat burgundy beef vegetable stew,"['weeknight', 'time-to-make', 'course', 'main-...","[280.1, 9.0, 36.0, 24.0, 59.0, 7.0, 7.0]","[beef eye round, vegetable oil, dried thyme le...",280.1,9.0,36.0,24.0,59.0,7.0,7.0
59,lou s fabulous bruschetta,"['60-minutes-or-less', 'time-to-make', 'course...","[221.5, 10.0, 7.0, 15.0, 16.0, 12.0, 10.0]","[french baguette, butter, garlic powder, ricot...",221.5,10.0,7.0,15.0,16.0,12.0,10.0
62,black bean corn and tomato salad,"['30-minutes-or-less', 'time-to-make', 'course...","[407.8, 23.0, 17.0, 0.0, 34.0, 11.0, 18.0]","[fresh lemon juice, olive oil, black bean, fre...",407.8,23.0,17.0,0.0,34.0,11.0,18.0
63,cabbage and sausage soup,"['60-minutes-or-less', 'time-to-make', 'course...","[586.1, 59.0, 46.0, 84.0, 60.0, 61.0, 8.0]","[olive oil, sausage, white onion, garlic, red ...",586.1,59.0,46.0,84.0,60.0,61.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...
536726,garlic prawn pasta,"['30-minutes-or-less', 'time-to-make', 'course...","[598.1, 27.0, 15.0, 24.0, 40.0, 33.0, 29.0]","[prawn, spaghettus, butter, olive oil, garlic ...",598.1,27.0,15.0,24.0,40.0,33.0,29.0
536990,slow cooker soy braised chicken,"['course', 'main-ingredient', 'preparation', '...","[655.4, 45.0, 35.0, 67.0, 84.0, 41.0, 17.0]","[onion, garlic clove, apple cider vinegar, soy...",655.4,45.0,35.0,67.0,84.0,41.0,17.0
537039,thanksgiving turkey meatloaf,"['time-to-make', 'course', 'main-ingredient', ...","[342.3, 24.0, 25.0, 23.0, 79.0, 23.0, 3.0]","[seasoned stuffing mix, milk, egg, onion, cele...",342.3,24.0,25.0,23.0,79.0,23.0,3.0
537458,garlic and herb mashed potatoes,"['60-minutes-or-less', 'time-to-make', 'course...","[390.8, 37.0, 12.0, 12.0, 11.0, 73.0, 12.0]","[yukon gold potato, cream cheese, butter, sour...",390.8,37.0,12.0,12.0,11.0,73.0,12.0
537716,mini buffalo chicken cheesesteaks,"['60-minutes-or-less', 'time-to-make', 'course...","[407.9, 34.0, 21.0, 49.0, 28.0, 64.0, 12.0]","[olive oil, green bell pepper, yellow onion, s...",407.9,34.0,21.0,49.0,28.0,64.0,12.0

In [55]:
beef_search = ['beef', 'hamburger', 'steak', 'veal', 'bison', 'beef sausage']
pork_search = ['pork', 'bacon', 'pancetta', 'boar', 'pork sausage']
chicken_search = ['chicken', 'turkey']
small_game_search = ['duck', 'pheasant', 'rabbit', 'quail', 'lapin', 'goose', 'grouse']
big_game_search = ['venison', 'deer', 'elk', 'caribou', 'moose']
seafood_search = ['fish', 
                  'shrimp',
                  'crab',
                  'salmon',
                  'tuna',
                  'swordfish',
                  'mackerel',
                  'bass',
                  'perch',
                  'oyster',
                  'scallop',
                  'lobster',
                  'prawn',
                  'squid',
                  'octopus',
                  'monkfish',
                  'black cod',
                  'trout',
                  'mahi-mahi', 
                  'pollock']

TypeError: unhashable type: 'list'